# Gradnja z malo RAM-a (sandbox 1 GB). Na obicajnem racunalniku povecaj.
org.gradle.jvmargs=-Xmx560m -XX:MaxMetaspaceSize=300m -XX:ReservedCodeCacheSize=48m -XX:+UseSerialGC -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
kotlin.incremental=true
kotlin.compiler.execution.strategy=in-process
kotlin.daemon.jvmargs=-Xmx380m -XX:MaxMetaspaceSize=240m -XX:+UseSerialGC
