# Standradne nastavitve za obicajne racunalnike (>= 8 GB RAM).
# V omejenem okolju (1 GB RAM) gradnja NI mozna -- glej docs/04-BUILD.md.
org.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=768m -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
kotlin.incremental=true
kotlin.daemon.jvmargs=-Xmx2048m
